### ISSUE TITLE
Exception: Error=(IP:192.168.32.229) 0x80a00105: 引数のデータタイプが不正

### ISSUE THREAD

**Issue by sazima** [freedomikeppp/mitsubishi-cnc-m700#2]
I created a file `test.py` 
```
from m700 import M700
# Open connection
# m700 = M700.get_connection('192.168.1.10:683')
m700 = M700.get_connection('192.168.32.229:1683')  # my m700 cnc

# NC内情報取得
m700.get_drive_infomation()
m700.get_run_status()
m700.get_alerm()

# Dデバイスへの操作
m700.write_dev('M900', 1)
m700.read_dev('M900') # -> 1

# Mデバイスへの操作
m700.write_dev('D200', 10)
m700.read_dev('D200') # -> 10

# 加工プログラムのファイルの操作（read・write・delete）
drivenm = m700.get_drive_infomation()
m700.write_file(drivenm + '¥PRG¥USER¥__TEST__.txt', b'TEST_WRITE')
m700.read_file(drivenm + '¥PRG¥USER¥__TEST__.txt')
m700.delete_file(drivenm + '¥PRG¥USER¥__TEST__.txt')

# Close connection
m700.close()
```

and an error is reported when running

```
python test.py

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    m700.get_drive_infomation()
  File "D:\project\mitsubishi-cnc-m700-master\m700.py", line 140, in get_drive_infomation
    self.__open()
  File "D:\project\mitsubishi-cnc-m700-master\m700.py", line 98, in __open
    self.__raise_error(errcd)
  File "D:\project\mitsubishi-cnc-m700-master\m700.py", line 831, in __raise_error
    raise Exception('Error=(IP:' + self.__ip + ') ' + hex_str + ': ' + msg)
Exception: Error=(IP:192.168.32.229) 0x80a00105: 引数のデータタイプが不正


```

**Comment by sazima** [comment]
Sorry, because the Mitsubishi model I connected is not M700。
